# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Etu < Formula
  desc "A personal command line journal"
  homepage "https://github.com/icco/etu"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/icco/etu/releases/download/v0.1.5/etu_0.1.5_darwin_amd64.tar.gz"
      sha256 "f91eea498869b1d33cf0298c6de0c77c50247b711253dadf33500cfdb04d68c1"

      def install
        bin.install "etu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/icco/etu/releases/download/v0.1.5/etu_0.1.5_darwin_arm64.tar.gz"
      sha256 "4b8cb408d3cde980f29a81f4d0c8f024c656e752649fa941d39f7e5155e00622"

      def install
        bin.install "etu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/icco/etu/releases/download/v0.1.5/etu_0.1.5_linux_amd64.tar.gz"
      sha256 "2bc4c84434e0709f4df0a405ae037e9273ff6beeec1c577f553c17ca4e9a205c"
      def install
        bin.install "etu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/icco/etu/releases/download/v0.1.5/etu_0.1.5_linux_arm64.tar.gz"
      sha256 "5795c3c77bef764327d216400a4fbe1b9bafa90d05c9309d2058eb8425ea22fb"
      def install
        bin.install "etu"
      end
    end
  end

  test do
    system "#{bin}/etu --version"
  end
end
