# This file was generated by GoReleaser. DO NOT EDIT.
cask "art" do
  version "0.12.1"

  on_macos do
    on_intel do
      sha256 "db6f7a965a92ac6d343a5b4273a2b8c16806d260475c49fdf51b41162ea2af52"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "019deef57c94f3c1129d5e9342ec2b13468a466c083480de1ea8e98052c33c02"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc6b0aab5cda9c50de322d2555cfcaf710e533600ac612d4744b15b669b5f393"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "abf72544cbce11551a19024cf70f6c54c93dc49ac84eaf7cf37900225b00a229"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_linux_arm64.tar.gz"
    end
  end

  name "art"
  desc "Personal scheduling agent — TUI for the art server"
  homepage "https://github.com/icco/art"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "art"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/art"]
    end
  end

  # No zap stanza required

end
