# This file was generated by GoReleaser. DO NOT EDIT.
cask "art" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "9ada6e86094c591383e62cb07dd37f2e635e826d02685f103f6643014ced43a3"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "23ca460c07a20e7489b33c1c6555752a04838f03276d27fa70b7e0d235791823"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6317ccf34e9fd1dfd4ae84d9b7b1934bc0e9eb05a1904e58385c85017efdbd77"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d1e933df585490b2dba2ff1428345af87adfe727b12a697e30cffa3bf208eac"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_linux_arm64.tar.gz"
    end
  end

  name "art"
  desc "Personal scheduling agent — TUI for the art server"
  homepage "https://github.com/icco/art"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "art"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/art"]
    end
  end

  # No zap stanza required

end
