# This file was generated by GoReleaser. DO NOT EDIT.
cask "art" do
  version "0.11.6"

  on_macos do
    on_intel do
      sha256 "ea48782f102de66b61890dfe004033770075163f0716c959619986cb584a47dd"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6fea96930b9fedd1ba7bc6cc759ed8503df853186a46ed5130abeacd91b203c"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bdc2d7ff4674ba2ac02e4e3cd9a8ff077e75aba14941c1325cee3fffa10667ca"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "29bc55d1149a7c7dfe0b421447888295ff22ee09586d8067d79b1a5c3cb3a743"
      url "https://github.com/icco/art/releases/download/v#{version}/art_#{version}_linux_arm64.tar.gz"
    end
  end

  name "art"
  desc "Personal scheduling agent — TUI for the art server"
  homepage "https://github.com/icco/art"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "art"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/art"]
    end
  end

  # No zap stanza required

end
