# This file was generated by GoReleaser. DO NOT EDIT.
cask "bugsim" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "2d02025335f594878f1fd35fb4154e03714f20d73ecfeff2aa5f79382b263fe5"
      url "https://github.com/icco/bugsim/releases/download/v#{version}/bugsim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7678cb82e9d48c8ecc5948e023123c286e8dc3ad43f8f872e4da7d455e48b61b"
      url "https://github.com/icco/bugsim/releases/download/v#{version}/bugsim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "80caf61009874253f821c88b93abee38fa98d91a2ea5ed1dd9a6faeee03dc9db"
      url "https://github.com/icco/bugsim/releases/download/v#{version}/bugsim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3654956c3af29601251b82f622ada74c00c4754a4a4c1524b049843a76799021"
      url "https://github.com/icco/bugsim/releases/download/v#{version}/bugsim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bugsim"
  desc "Terminal flight simulator for software engineers"
  homepage "https://github.com/icco/bugsim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bugsim"
  bash_completion "completions/bugsim.bash"
  fish_completion "completions/bugsim.fish"
  zsh_completion "completions/_bugsim"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bugsim"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    bugsim runs each implement-track pack inside a Docker container.
    Install and start Docker before running `bugsim play`.

    Seed packs are not bundled with the cask. Either clone
    https://github.com/icco/bugsim and pass `--packs ./packs`, or
    point `--packs` at any directory of pack subdirectories.
  EOS
end
