# This file was generated by GoReleaser. DO NOT EDIT.
cask "bugsim" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c9d2aa3b919aa4a013a18dd9bb357046e41762f4c8e5ae4dc80f4d8b899b1da0"
      url "https://github.com/icco/bugsim/releases/download/v#{version}/bugsim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b55fa9468ca0388af4b8bc704673b703f721d1b509cb53029ccf0bb76eeb8f5a"
      url "https://github.com/icco/bugsim/releases/download/v#{version}/bugsim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a165b94b9edad96ffd355d0ea2f841522bf1890c1f637b96eac6cb82729fd520"
      url "https://github.com/icco/bugsim/releases/download/v#{version}/bugsim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "759c10eb37b1848282428f61c7bab7dd5cbd4a6511f8a2167d82e981570624f3"
      url "https://github.com/icco/bugsim/releases/download/v#{version}/bugsim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bugsim"
  desc "Terminal flight simulator for software engineers"
  homepage "https://github.com/icco/bugsim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bugsim"
  bash_completion "completions/bugsim.bash"
  fish_completion "completions/bugsim.fish"
  zsh_completion "completions/_bugsim"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bugsim"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    bugsim runs each implement-track pack inside a Docker container.
    Install and start Docker before running `bugsim play`.

    Seed packs are not bundled with the cask. Either clone
    https://github.com/icco/bugsim and pass `--packs ./packs`, or
    point `--packs` at any directory of pack subdirectories.
  EOS
end
