# This file was generated by GoReleaser. DO NOT EDIT.
cask "etu" do
  version "1.5.10"

  on_macos do
    on_arm do
      sha256 "261593b7753647017b09b8cfb418bc0ad82248edbd9e26b5bf0a2e9e08d22f91"
      url "https://github.com/icco/etu/releases/download/v#{version}/etu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9e26990396258c3986136608098d4d6bf4bca4a72b08ae891b75c9aab833850f"
      url "https://github.com/icco/etu/releases/download/v#{version}/etu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "44070e9f094b81f5d3951872f48aeceb27ce73f5f05df4982ed11153630aa161"
      url "https://github.com/icco/etu/releases/download/v#{version}/etu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5d560037c90fa2cb2110f86f17b1d7ee7ca4bb2a006a8395ab2db3a6436daed"
      url "https://github.com/icco/etu/releases/download/v#{version}/etu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "etu"
  desc "A personal command line journal"
  homepage "https://github.com/icco/etu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "etu"
  bash_completion "completions/etu.bash"
  fish_completion "completions/etu.fish"
  zsh_completion "completions/_etu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/etu"]
    end
  end

  # No zap stanza required
end
