# This file was generated by GoReleaser. DO NOT EDIT.
cask "etu" do
  name "etu"
  desc "A personal command line journal"
  homepage "https://github.com/icco/etu"
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "etu"

  on_macos do
    on_intel do
      url "https://github.com/icco/etu/releases/download/v#{version}/etu_#{version}_darwin_amd64.tar.gz"
      sha256 "dfcbfab31827f38b87c347d66a55de2f18eb7f8184a589daaa4e866d867c4bd0"
    end
    on_arm do
      url "https://github.com/icco/etu/releases/download/v#{version}/etu_#{version}_darwin_arm64.tar.gz"
      sha256 "0a768968920bd8c94cc62af26edf7212f60873a9a08d9f19163d5212ae8ca04d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/icco/etu/releases/download/v#{version}/etu_#{version}_linux_amd64.tar.gz"
      sha256 "d05186136027f48bada11b70550dd795f56d47cb73ccd91e7ab8d54974bccf6e"
    end
    on_arm do
      url "https://github.com/icco/etu/releases/download/v#{version}/etu_#{version}_linux_arm64.tar.gz"
      sha256 "032ccba562231fee55f42f2485e6c807bdea2069bd98c434ae2612dbdd46ed8b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/etu"]
    end
  end

  # No zap stanza required
end
