# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitstatus" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "0ce5cb1d47aeb720b6b97f60f2b568fde12ca5c5ae50997fa348ff13d5733258"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cdc963b2778ceb59ca9a94b967f08e5a255bee9be19e2b8d8219a5a64e4be501"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0274d983d41eef713f4aab2cefbcb8d638e27a3321fb330b110303c1b7da3fc9"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ac89f020f2c4de36f639f2a3c67f41d6d667bb0a81a733e0acaa80b2f162c07"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitstatus"
  desc "Git repository status as one line, for a shell prompt"
  homepage "https://github.com/icco/gitstatus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitstatus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitstatus"]
    end
  end

  # No zap stanza required
end
