# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitstatus" do
  version "1.0.3"

  on_macos do
    on_arm do
      sha256 "8127c13978e69f21c73e694c0484580fcabc6f1cc887db6d7a9eef7b49d1e9c8"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "01a375f88413359e826f3da09bd7704f18af733217830a2e40b4ca8149b36160"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a26d223f79c6cb0e76a9ef06ca580cea2e391e24eae27f6fde0bca394235992e"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "22cc5ca7adf41437ad2fc62d27d231e5cac5bba1bea86e6442e53272be79c152"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitstatus"
  desc "Git repository status as one line, for a shell prompt"
  homepage "https://github.com/icco/gitstatus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitstatus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitstatus"]
    end
  end

  # No zap stanza required
end
