# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitstatus" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "403b278196bc1f9880cbd2f29f3b01c27a87d096a1069a69fab03e75a1549de1"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ba3bc099c9a3e4a9170979d6b885e052ffc8f52b345909e26bc5edb54d563575"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fe323e31dea64b75fe852838179f50de1fd3ff632d170ed749785536d78a6b2d"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "018a2f26a067875fafaa149f72eafdd61f2aefbb0e9f300e5cbdc73615859077"
      url "https://github.com/icco/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitstatus"
  desc "Git repository status as one line, for a shell prompt"
  homepage "https://github.com/icco/gitstatus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitstatus"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gitstatus"]
    end
  end

  # No zap stanza required
end
