# This file was generated by GoReleaser. DO NOT EDIT.
cask "gotak" do
  version "0.5.5"

  on_macos do
    on_intel do
      sha256 "1a6c7253f079ff9c2aa504771ed208104b3b99266cdc0f6d31084520eb5d6034"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "604b40b5574311203b2e24ada226d92214d52d26ca7ca06dd7efaf71850cbba5"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9dce30926a7e73c3a19be2cba342cdb01ff151f7ca1f263ca170a62737599ed5"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1af0f691d84844a99d361bb5dcaa9480f0539c29f3ed74fc9334a0da91945079"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gotak"
  desc "A CLI client for the Tak board-game server"
  homepage "https://github.com/icco/gotak"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gotak"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gotak"]
    end
  end

  # No zap stanza required

end
