# This file was generated by GoReleaser. DO NOT EDIT.
cask "gotak" do
  version "0.5.10"

  on_macos do
    on_arm do
      sha256 "09f6a49ec9cf8787e4a6ca12d9bed32ebe4cc6dc94ed8b5b274ad67513d52889"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "980ee99f2e6b5ff2aa3f1b22ec1d76f30832cd0b095ccce95f32f1e4b1b5102b"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9c99e3b6c8b1a02355817098e6e4e9b9fb214e70c4ea008027e5dc8f2901d675"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f645406beeefca96e1f3acd8395f0b1c83dcc8f5e1675e1e53e02e6081aa8c77"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gotak"
  desc "A CLI client for the Tak board-game server"
  homepage "https://github.com/icco/gotak"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gotak"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gotak"]
    end
  end

  # No zap stanza required
end
