# This file was generated by GoReleaser. DO NOT EDIT.
cask "gotak" do
  version "0.5.15"

  on_macos do
    on_arm do
      sha256 "173e0ea4d7344875e2f38da2ead07ccc40e7f7fd9ca4694fa53dec014831cd01"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2bd7c547f38ce44d59d34783bcdeabce3978b07b20fefb93a9b26ce8ba5fd1d6"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b6dd9f38974cd66df23cd4f4fdb461d3a7d77e1a23db082be1baf11f69df7a6b"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "17d1b383cc4d1c976eb3340b3ff1fcdecd63174ac0379ee472379cd65d905a9d"
      url "https://github.com/icco/gotak/releases/download/v#{version}/gotak_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gotak"
  desc "A CLI client for the Tak board-game server"
  homepage "https://github.com/icco/gotak"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gotak"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gotak"]
    end
  end

  # No zap stanza required
end
