# This file was generated by GoReleaser. DO NOT EDIT.
cask "where" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "cb05b8641551a0def8255d221fda4031137fbbe83cc8ace62c6a9299efc40817"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e7f94b0ffb3abd395763400aafcd03354ecf3046826b9ca4182048424200f9d8"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "507098bbf54d2d6dd7b02a80f22afed6e85f6d4d6649c91af73f8cbb92027210"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b63e734d0abc69bc3f85f2941c4eaaac3958da99130949904417bd66d32176c"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_linux_amd64.tar.gz"
    end
  end

  name "where"
  desc "Shared locations and local times for your people"
  homepage "https://github.com/icco/where"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "where"
  bash_completion "completions/where.bash"
  fish_completion "completions/where.fish"
  zsh_completion "completions/_where"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/where"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    In zsh, use `command where` to bypass the shell's built-in `where`. Google uses imported Maps browser cookies. Apple requires a signed-in macOS Find My session and Accessibility/Automation permission.
  EOS
end
