# This file was generated by GoReleaser. DO NOT EDIT.
cask "where" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "cd4465ccb9504e262e78e0915468da334220f82cfd916945922ba706dbd3f349"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d131d79191dbadda4489bf3223bc35b5fe6d1817ee78d64c29abea22ab1f8c3f"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f863fa49b6d0b84f488cf69f715d0fa26334c5408e946f66f4fcaef7e46565d9"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "48362b83ae32c8898bccadd762c2c02468b2f399abdc876b95a83c6748669a38"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_linux_amd64.tar.gz"
    end
  end

  name "where"
  desc "Shared locations and local times for your people"
  homepage "https://github.com/icco/where"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "where"
  bash_completion "completions/where.bash"
  fish_completion "completions/where.fish"
  zsh_completion "completions/_where"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/where"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    In zsh, use `command where` to bypass the shell's built-in `where`. Google uses imported Maps browser cookies. Apple requires a signed-in macOS Find My session and Accessibility/Automation permission.
  EOS
end
