# This file was generated by GoReleaser. DO NOT EDIT.
cask "where" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "d731ffcdae95c5af3d5e2431bdecbef13f86c78e46bee1db1e5520f09d8a278f"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "77b608f277a38ce0e46ef68ac28a2ba4ed69d5c42508e9b9e001ad1cf3722e64"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "97f8be8dec7f396e7557459cf009c7729ea613e098c076a2d495b3c0a359db05"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ab14e614ecd4c378d0b5e59f3bb003d24e50f368687fd59b5d1ffcf4e92b80e7"
      url "https://github.com/icco/where/releases/download/v#{version}/where_#{version}_linux_amd64.tar.gz"
    end
  end

  name "where"
  desc "Shared locations and local times for your people"
  homepage "https://github.com/icco/where"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "where"
  bash_completion "completions/where.bash"
  fish_completion "completions/where.fish"
  zsh_completion "completions/_where"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/where"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    In zsh, use `command where` to bypass the shell's built-in `where`. Google uses imported Maps browser cookies. Apple requires a signed-in macOS Find My session and Accessibility/Automation permission.
  EOS
end
